"""create users and services

Revision ID: 50a43375b646
Revises: 
Create Date: 2025-12-22 11:31:04.510490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a43375b646'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_services_id'), 'services', ['id'], unique=False, schema='SWORD')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_users_id'), 'users', ['id'], unique=False, schema='SWORD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SWORD_users_id'), table_name='users', schema='SWORD')
    op.drop_table('users', schema='SWORD')
    op.drop_index(op.f('ix_SWORD_services_id'), table_name='services', schema='SWORD')
    op.drop_table('services', schema='SWORD')
    # ### end Alembic commands ###
