"""add description to services

Revision ID: 5bd52141fa53
Revises: c1d7ae9cf29d
Create Date: 2025-12-22 15:45:23.579895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd52141fa53'
down_revision: Union[str, Sequence[str], None] = 'c1d7ae9cf29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('description', sa.Text(), nullable=True), schema='SWORD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'description', schema='SWORD')
    # ### end Alembic commands ###
