"""add_provider_id_to_services

Revision ID: 778050fd420d
Revises: add_role_id_to_users
Create Date: 2026-01-08 13:53:13.614546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778050fd420d'
down_revision: Union[str, Sequence[str], None] = 'add_role_id_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_id'), table_name='roles', schema='SWORD')
    op.create_index(op.f('ix_SWORD_roles_id'), 'roles', ['id'], unique=False, schema='SWORD')
    op.add_column('services', sa.Column('provider_id', sa.Integer(), nullable=False), schema='SWORD')
    op.create_foreign_key(None, 'services', 'users', ['provider_id'], ['id'], source_schema='SWORD', referent_schema='SWORD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', schema='SWORD', type_='foreignkey')
    op.drop_column('services', 'provider_id', schema='SWORD')
    op.drop_index(op.f('ix_SWORD_roles_id'), table_name='roles', schema='SWORD')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False, schema='SWORD')
    # ### end Alembic commands ###
