"""add_orders_table

Revision ID: 851ccaec12e0
Revises: e20fa45e5102
Create Date: 2026-01-13 13:41:42.733802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851ccaec12e0'
down_revision: Union[str, Sequence[str], None] = 'e20fa45e5102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['SWORD.services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['SWORD.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_orders_id'), 'orders', ['id'], unique=False, schema='SWORD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SWORD_orders_id'), table_name='orders', schema='SWORD')
    op.drop_table('orders', schema='SWORD')
    # ### end Alembic commands ###
