"""rename orders table to requests

Revision ID: a35cadab734f
Revises: 851ccaec12e0
Create Date: 2026-01-28 11:18:01.650399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35cadab734f'
down_revision: Union[str, Sequence[str], None] = '851ccaec12e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['SWORD.services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['SWORD.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_requests_id'), 'requests', ['id'], unique=False, schema='SWORD')
    op.drop_index(op.f('ix_SWORD_orders_id'), table_name='orders', schema='SWORD')
    op.drop_table('orders', schema='SWORD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['SWORD.services.id'], name=op.f('orders_service_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['SWORD.users.id'], name=op.f('orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey')),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_orders_id'), 'orders', ['id'], unique=False, schema='SWORD')
    op.drop_index(op.f('ix_SWORD_requests_id'), table_name='requests', schema='SWORD')
    op.drop_table('requests', schema='SWORD')
    # ### end Alembic commands ###
