"""removed unique password

Revision ID: c1d7ae9cf29d
Revises: 50a43375b646
Create Date: 2025-12-22 11:39:17.646089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d7ae9cf29d'
down_revision: Union[str, Sequence[str], None] = '50a43375b646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_password_key'), 'users', schema='SWORD', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_password_key'), 'users', ['password'], schema='SWORD', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
