"""init

Revision ID: c26dc5fcaeb7
Revises: 
Create Date: 2026-01-05 15:30:16.231486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26dc5fcaeb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_services_id'), 'services', ['id'], unique=False, schema='SWORD')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_users_id'), 'users', ['id'], unique=False, schema='SWORD')
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['SWORD.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_addresses_id'), 'addresses', ['id'], unique=False, schema='SWORD')
    op.create_index(op.f('ix_SWORD_addresses_user_id'), 'addresses', ['user_id'], unique=False, schema='SWORD')
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['SWORD.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_personal_access_tokens_id'), 'personal_access_tokens', ['id'], unique=False, schema='SWORD')
    op.create_index(op.f('ix_SWORD_personal_access_tokens_user_id'), 'personal_access_tokens', ['user_id'], unique=False, schema='SWORD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SWORD_personal_access_tokens_user_id'), table_name='personal_access_tokens', schema='SWORD')
    op.drop_index(op.f('ix_SWORD_personal_access_tokens_id'), table_name='personal_access_tokens', schema='SWORD')
    op.drop_table('personal_access_tokens', schema='SWORD')
    op.drop_index(op.f('ix_SWORD_addresses_user_id'), table_name='addresses', schema='SWORD')
    op.drop_index(op.f('ix_SWORD_addresses_id'), table_name='addresses', schema='SWORD')
    op.drop_table('addresses', schema='SWORD')
    op.drop_index(op.f('ix_SWORD_users_id'), table_name='users', schema='SWORD')
    op.drop_table('users', schema='SWORD')
    op.drop_index(op.f('ix_SWORD_services_id'), table_name='services', schema='SWORD')
    op.drop_table('services', schema='SWORD')
    # ### end Alembic commands ###
