"""create refresh access token

Revision ID: d5ee24f6f71c
Revises: 06f6f80e863d
Create Date: 2025-12-23 18:08:10.459685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ee24f6f71c'
down_revision: Union[str, Sequence[str], None] = '06f6f80e863d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['SWORD.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token'),
    schema='SWORD'
    )
    op.create_index(op.f('ix_SWORD_personal_access_tokens_user_id'), 'personal_access_tokens', ['user_id'], unique=False, schema='SWORD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SWORD_personal_access_tokens_user_id'), table_name='personal_access_tokens', schema='SWORD')
    op.drop_table('personal_access_tokens', schema='SWORD')
    # ### end Alembic commands ###
