"""add_new_columns_to_services_and_users

Revision ID: e20fa45e5102
Revises: 778050fd420d
Create Date: 2026-01-12 13:40:33.827333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20fa45e5102'
down_revision: Union[str, Sequence[str], None] = '778050fd420d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('price', sa.Integer(), nullable=False), schema='SWORD')
    op.add_column('services', sa.Column('status', sa.Boolean(), nullable=False), schema='SWORD')
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='SWORD')
    op.drop_constraint(op.f('services_name_key'), 'services', schema='SWORD', type_='unique')
    op.add_column('users', sa.Column('website', sa.String(length=150), nullable=True), schema='SWORD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website', schema='SWORD')
    op.create_unique_constraint(op.f('services_name_key'), 'services', ['name'], schema='SWORD', postgresql_nulls_not_distinct=False)
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='SWORD')
    op.drop_column('services', 'status', schema='SWORD')
    op.drop_column('services', 'price', schema='SWORD')
    # ### end Alembic commands ###
